name: Waka Readme

on:
  workflow_dispatch: # 수동으로 Workflow 실행
  schedule:
    - cron: "0 15 * * *" # 매일 오전 12시 (한국 시간 기준)

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIME_RANGE: last_30_days
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          SHOW_TITLE: true
        
